[package]
name = "AMM"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/asymptotic-code/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "next", override = true }

[addresses]
amm = "0x0"
